### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by KendrickAng** [claudiogreco/coling18-gte#1]
Hi, I met this error when trying to run the code:
```
. (while training..)
.
.
Step 169: loss = 18.46 (286.694 sec)
Validation Data Eval:
correct_tags: 1068.0    total_tags: 2999.0
Current accuracy on dev is 35.61
Best accuracy on dev set is 41.01
Decoding on the test set:
('with_mean_aggregation: ', True)
WARNING:tensorflow:From main.py:403: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
Traceback (most recent call last):
  File "main.py", line 479, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/kendrick/anaconda3/envs/bimpm/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 414, in main
    accuracy = evaluate(testDataStream, valid_graph, sess, outpath=FLAGS.suffix+ FLAGS.train + FLAGS.test + ".result",char_vocab=char_vocab,label_vocab=label_vocab, word_vocab=word_vocab)
  File "main.py", line 120, in evaluate
    outline = label_batch[i] + "\t" + label_vocab.getWord(predictions[i]) + "\t" + sent1_batch[i] + "\t" + sent2_batch[i] + '\t' + img_id_batch[i] + "\n"
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

My config file is as follows:
```
{
    "dropout_rate": 0.1,
    "suffix": "snli_text_only_hypo",
    "NER_dim": 20,
    "highway_layer_num": 1,
    "with_match_highway": true,
    "optimize_type": "adam",
    "with_highway": true,
    "max_epochs": 10,
    "with_aggregation_highway": true,
    "with_filter_layer": false,
    "lex_decompsition_dim": -1,
    "aggregation_layer_num": 1,
    "max_char_per_word": 10,
    "wo_maxpool_match": false,
    "context_layer_num": 1,
    "wo_full_match": false,
    "lambda_l2": 0.0,
    "fix_word_vec": true,
    "wo_left_match": false,
    "with_NER": false,
    "aggregation_lstm_dim": 300,
    "context_lstm_dim": 100,
    "POS_dim": 20,
    "with_lex_decomposition": false,
    "learning_rate": 0.001,
    "with_POS": false,
    "wo_right_match": false,
    "MP_dim": 10,
    "max_sent_length": 100,
    "batch_size": 180,
    "wo_max_attentive_match": false,
    "wo_char": false,
    "wo_attentive_match": false,
    "char_emb_dim": 20,
    "with_img_full_match":false,
    "with_img_maxpool_match":false,
"with_img_attentive_match":false,
    "with_img_max_attentive_match":false,
    "image_context_layer" : false,
    "image_with_hypothesis_only": false,
    "img_dim":100,
    "char_lstm_dim": 100,
    "word_level_MP_dim": -1,
    "base_dir": "./snli",
    "model_dir" : "models",
    "with_dep" : false,
    "beginning": false,
    "with_image": false,
    "train_path": "../dataset/VSNLI_1.0_train.tsv",
    "test_path": "../dataset/VSNLI_1.0_test.tsv",
    "dev_path": "../dataset/VSNLI_1.0_dev.tsv",
    "word_vec_path" : "/home/kendrick/TE/bimpm-te/coling18-gte/glove.840B.300d.txt",
    "decoding_only": false,
    "train" : "snli",
    "test" : "train"
}
```
Is it due to invalid configurations, or will i need to change part of the code?

I'm running it on python 2.7, tensorflow 1.0, following the instructions as listed.

**Comment by claudiogreco** [comment]
Hi,

sorry for the delay. The configuration file looks fine. Could you try running the code on Python 3 and tell me whether you still get that error?

Claudio
